/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/human.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.mixamorig1Hips} />
      <skinnedMesh geometry={nodes.Ch36.geometry} material={materials.Ch36_Body} skeleton={nodes.Ch36.skeleton} />
    </group>
  )
}

useGLTF.preload('/human.glb')
